version 2.1

jobs
  build: 
   docker:
   -image: node:20.3.1
  steps:
   - checkout
   - run:
      name: "Run test"
      command: npm test
      environment:
            HEAD_LESS: true

   workflows:
    build_now:
     jobs:
       - build
   
  