version 2.1

jobs
  build: 
    docker:
    -image: node:20.3.1
    environment:
      HEAD_LESS: true
      
    steps:
    - run:
        name: "Setup JRE"
        command: |
          apt-get install default-jre
    - checkout
    - run:
          name: "Run test"
          command: |
            echo 'export HEAD_LESS="true"'
            echo ${HEAD_LESS}
            npm test
    workflows:
      build_now:
      jobs:
        - build
   
  