version: 2.1

jobs:
  build: 
    docker:
    - image: node:20.3.1
    environment:
      HEAD_LESS: true
      
    steps:
    - run:
        name: "Setup chrome"
        command: |
          curl https://intoli.com/install-google-chrome.sh | bash
    - checkout
    - run: npm install
    - run:
          name: "Run test"
          command: |
            npm test
  
workflows:
  build_now:
    jobs:
      - build
  
  